### PR TITLE
Who just uses a kernel?

### PR DESCRIPTION
**Pull request by deavmi**

### CODE REVIEW

**Comment by MathJud** [comment]
Hmm. I think it is easier and more understandable the way it is. 
All the other OSs are also represented with only one word ...

**Comment by deavmi** [comment]
@MathJud Most people call GNU/Linux (the OS) Linux, i see why, but we need to change that ugly habbit.

**Comment by deavmi** [comment]
@MathJud What is cherry picking, it's part of git right? :smile:

**Comment by MathJud** [comment]
cherry picking is the possibility in git to include single commits, instead of an entire repository or merge request. I only included the spelling fix commit and not the entire merge request with all commits.

**Comment by deavmi** [comment]
Oh okay

**Pull request closed without merging**
