### PR TITLE
Update README.md [RaspberryPi]

### PR DESCRIPTION
**Pull request by deavmi**

### CODE REVIEW

**Comment by MathJud** [comment]
What should the lines with ```` be good for?

**Comment by deavmi** [comment]
It shows that the text inclosed in them is code, and makes the text suit the code sytling of markdown

**Comment by deavmi** [comment]
@MathJud It makes the code more reabable.

**Comment by MathJud** [comment]
The idea behind these markdown files is, that the markdown format is understandable when read in a simple text editor. Markdown has been developed for this use case and is the wiki / documentation syntax of choice for all the programmers. 
Indentation is the default syntax used for code formatting. It is the syntax of choice as it easily writable and readable in a text editor. The proposed syntax here does IMHO not add any additional feature and makes the text file not very easily readable / copy pastable.

**Comment by deavmi** [comment]
@MathJud Okay. :smile:

**Pull request closed without merging**
